name: Tests run

on:
    issue_comment:
        types: [edited]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Add comment to PR
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ github.event.issue.number }}
            header: cypress
            message: |
                Running Cypress e2e tests...
      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: binary-com/vercel-preview-url-action@v1.0.5
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v1
      - name: Write the cypress.env.json file ðŸ“
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: Run Cypress ðŸŒ²
        uses: cypress-io/github-action@v4
        env:
          # use the deployment_url variable to set the url
          CYPRESS_BASE_URL: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
